name: frog_list
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Functional Packages
  shared_preferences: 2.2.2
  flutter_bloc: 8.1.3
  get_it: 7.6.7
  dartz: 0.10.1
  equatable: 2.0.5

  ## Visual Packages
  cupertino_icons: 1.0.6
  google_fonts: 6.1.0
  shimmer_animation: 2.1.0+1
  loading_animation_widget: 1.2.0+4
  msh_checkbox: 2.0.1
  animated_line_through: 1.0.4
  flutter_staggered_animations: 1.1.1

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1

  ## Test Packages
  mockito: 5.4.4
  build_runner: 2.4.8
  bloc_test: 9.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
